### ISSUE TITLE
Alerts are missing the alert-dismissible class

### ISSUE THREAD

**Issue by xt0rted** [olsh/resharper-bootstrap-templates#2]
Since alerts have the dismiss button the parent div should also include the `alert-dismissible` class.

http://getbootstrap.com/components/#alerts-dismissible

``` html
<div class="alert alert-success alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <strong>Title!</strong> Alert body ...
</div>
```

Maybe there should be two templates, one with the dismiss button, and one without.

**Comment by olsh** [comment]
@xt0rted Thanks for the report.
I've added a separate template for dismissible.
You can find all the templates here
https://github.com/olsh/resharper-bootstrap-templates/tree/master/templates/bs3
