### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by square-unit** [olsh/resharper-bootstrap-templates#3]
Hi All,

I'm support engineer of ReSharper team. For the current Bootstrap 4 Live Templates version, R# 2018.1.1 fails to install the plugin with the errors.

[exceptions.txt](https://github.com/olsh/resharper-bootstrap-templates/files/2068552/exceptions.txt)
--
Andrey Simukov
Support Engineer
JetBrains
http://www.jetbrains.com
The Drive To Develop
andrey.simukov@jetbrains.com

**Comment by olsh** [comment]
Hi @square-unit
Thank you for the reporting.
Fixed in 2018.1.2.21, could you please try to install 2018.1.2.21 and let me know if the issue was resolved?

**Comment by square-unit** [comment]
Hi @olsh,

I'm not aware if the issue was 100% reproducible. However I don't get any errors in my environment. Thank you for the fix!

**Comment by olsh** [comment]
Thanks for letting me know, closing this out.
Feel free to reopen the issue if the bug still appears.
