### ISSUE TITLE
Support updated wave for Resharper v 2020.2.4 and 2020.3

### ISSUE THREAD

**Issue by MADCookie** [olsh/resharper-bootstrap-templates#4]
I'm new to Resharper plugins. My Resharper is v 2020.2.4, which I think is called wave 203.0.0.

I forked your project to try to bump up support, but I'm too new to this process to get it to work correctly to submit you a pull request.

Do you plan to release updates that support the latest wave and the next wave that is right around the corner for Researcher 2020.3?

If you write up a markdown file on how I (or others) could contribute, then I'd be happy to help out and you can review the PR.

**Comment by olsh** [comment]
Hi @MADCookie,

Thanks for the interest in the project.
The updating process is pretty straightforward. Please check the last commit.
https://github.com/olsh/resharper-bootstrap-templates/commit/9ae8378b64c41170f32c42899a645ba65c4dc7a8

I would be glad accept PR on updating the readme file ;)

**Comment by olsh** [comment]
I've improved the updating flow, now @dependabot will do this automatically https://github.com/olsh/resharper-bootstrap-templates/pull/5
